version: "3.8"

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: techcaesar
      POSTGRES_PASSWORD: 11111968.Gold
      POSTGRES_DB: schoolsync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://techcaesar:11111968.Gold@localhost:5432/schoolsync
    depends_on:
      - postgres

volumes:
  postgres_data:
